pr: none
trigger: none

pool:
  vmImage: 'windows-latest'

variables:
 - name: BuildingInVsts
   value: true
 - name: SolutionDirectory
   value: 'src\FiscalIntegration\PosFiscalConnectorSample'

steps:
  - task: PowerShell@2
    displayName: 'Pre-Build steps'
    inputs:
      targetType: filePath
      filePath: ./Pipeline/PowershellScripts/Pre-Build.ps1
      failOnStderr: true

  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet 5.4.0'
    inputs:
      versionSpec: '5.4.0'

  - task: NuGetCommand@2
    displayName: 'NuGet restore'
    inputs:
      feedsToUse: config
      nugetConfigPath: nuget.config

  - task: VSBuild@1
    displayName: 'Build solution Contoso.PosFiscalConnectorSample.sln'
    inputs:
      solution: '$(Build.SourcesDirectory)\$(SolutionDirectory)\Contoso.PosFiscalConnectorSample.sln'

  - task: DotNetCoreCLI@2
    displayName: 'Install AzureSignTool'
    inputs:
      command: custom
      custom: tool
      arguments: 'install --global azuresigntool'

  - task: PowerShell@2
    displayName: 'Copy CloudScaleUnitExtensionPackage package to artifact directory'
    inputs:
      targetType: filePath
      filePath: ./Pipeline/PowershellScripts/CopyFileToDestination.ps1
      arguments: '-RelativePath "$(Build.SourcesDirectory)\$(SolutionDirectory)\ScaleUnit\ScaleUnit" -File "CloudScaleUnitExtensionPackage.zip" -DestinationFullName "$(Build.ArtifactStagingDirectory)\ScaleUnitPackage_$(Build.BuildNumber).zip"'

  - task: PowerShell@2
    displayName: 'Copy Scale Unit Installer to Artifact directory'
    inputs:
      targetType: filePath
      filePath: ./Pipeline/PowerShellScripts/CopyFileToDestination.ps1
      arguments: '-RelativePath "$(Build.SourcesDirectory)\$(SolutionDirectory)\ScaleUnit\ScaleUnit.Installer" -File "Contoso.PosFiscalConnectorSample.ScaleUnit.Installer.exe" -DestinationFullName "$(Build.ArtifactStagingDirectory)\Contoso.PosFiscalConnectorSample.ScaleUnit.Installer_$(Build.BuildNumber).exe"'

  - task: PowerShell@2
    displayName: 'Copy Store Commerce Installer to Artifact directory'
    inputs:
      targetType: filePath
      filePath: ./Pipeline/PowerShellScripts/CopyFileToDestination.ps1
      arguments: '-RelativePath "$(Build.SourcesDirectory)\$(SolutionDirectory)\StoreCommerce.Installer" -File "Contoso.PosFiscalConnectorSample.StoreCommerce.Installer.exe" -DestinationFullName "$(Build.ArtifactStagingDirectory)\Contoso.PosFiscalConnectorSample.StoreCommerce.Installer_$(Build.BuildNumber).exe"'

  - task: PowerShell@2
    displayName: 'Sign Files'
    inputs:
      targetType: filePath
      filePath: ./Pipeline/PowerShellScripts/CodeSign.ps1
      arguments: '-AzureKeyVaultURI $(AzureKeyVaultURI) -ApplicationId $(ApplicationId) -ApplicationSecretValue $(SecretValue) -CertificateName $(CertificateName) -Timestamp $(Timestamp) -TimestampDigest "sha256" -Files "$(Build.ArtifactStagingDirectory)\Contoso.PosFiscalConnectorSample.ScaleUnit.Installer_$(Build.BuildNumber).exe $(Build.ArtifactStagingDirectory)\Contoso.PosFiscalConnectorSample.StoreCommerce.Installer_$(Build.BuildNumber).exe"'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'