--- 
blank_issues_enabled: false
contact_links: 
  - 
    about: "Please ask and answer usage questions in the Q&A category the Discussions page."
    name: Question
    url: "https://github.com/microsoft/Dynamics365Commerce.Solutions/discussions/categories/q-a"
  - 
    about: "Please use Lifecycle Services (LCS) to get help for any issues that are not related to Commerce extension development."
    name: Other issues
    url: "https://lcs.dynamics.com"